version: "3.5"

services:

  traefik:
    image: "traefik:v2.2.0"
    container_name: "traefik"
    networks: 
      - ownnet
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - traefik.frontend.rule=Host(`traefik.${SITE_DOMAIN}`)
      - traefik.port=8080
         
  portainer:
    image: "portainer/portainer-ce"
    container_name: "portainer"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/srv/portainer:/data"
    ports:
      - "8000:8000"
      - "80:9000"
    networks:
      - ownnet
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=http
      - traefik.http.routers.portainer.rule=Host(`portainer.${SITE_DOMAIN}`)
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000


  gitlab:
    image: 'ulm0/gitlab:latest'
    container_name: "gitlab"
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.${SITE_DOMAIN}'
        nginx['listen_port'] = 80
        # nginx['custom_gitlab_server_config'] = "location /-/plantuml/ { \n    proxy_cache off; \n    proxy_pass  http://plantuml:8090/; \n}\n"
    volumes:
      - "/srv/gitlab/config:/etc/gitlab"
      - "/srv/gitlab/logs:/var/log/gitlab"
      - "/srv/gitlab/data:/var/opt/gitlab"
    ports:
      - "23:22"
      - "81:80"
    networks:
      - ownnet
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitlab.entrypoints=http
      - traefik.http.routers.gitlab.rule=Host(`gitlab.${SITE_DOMAIN}`)
      - traefik.http.routers.gitlab.service=gitlab
      - traefik.http.services.gitlab.loadbalancer.server.port=80
  
networks:
  ownnet:
    driver: bridge
